import DEFINITIONS from './definitions';

const {
  ARCHITECTURE,
  AUTHENTICATION,
  CI_CD: { GHA },
  DATABASE: { SQL, MONGODB_MONGOOSE },
  HEADLESS_CMS: { GATSBY },
  QUERYING: { GRAPHQL, APOLLO },
  SECURITY,
  SERVER_SIDE: { NODE_EXPRESS , SSR },
  STATE_MANAGEMENT: { REDUX },
  STATIC_TYPES: { TYPESCRIPT },
  TESTING: { JEST, CYPRESS, REACT_TESTING_LIBRARY },
  TOOLS: { ESLINT, PRETTIER },
  UI: { REACT, NEXT_JS },
  VANILLA_JS
} = DEFINITIONS;

// TODO: Open source?

export const TECHNICAL_SKILLS = {
  SUMMARY: [
    VANILLA_JS,
    TYPESCRIPT,
    NODE_EXPRESS,
    ARCHITECTURE,
    REACT,
    NEXT_JS,
    SQL,
    MONGODB_MONGOOSE,
    GRAPHQL,
    APOLLO,
    SSR,
    REDUX,
    JEST,
    CYPRESS,
    REACT_TESTING_LIBRARY,
    SECURITY,
    AUTHENTICATION,
    ESLINT,
    PRETTIER,
    GHA,
    GATSBY
  ]
};

export default TECHNICAL_SKILLS;
