import DEFINITIONS from './definitions';

const {
  ARCHITECTURE,
  CI_CD,
  CLIENT_AND_SERVER_SIDE,
  HEADLESS_CMS,
  HISTORICAL,
  MISCELLANEOUS,
  SECURITY,
  SERVER_SIDE_DATABASES,
  STYLING,
  SYSTEM_INTEGRATIONS,
  TESTING,
  TOOLS_DOCUMENTATION,
  TYPESCRIPT,
  UI,
  VANILLA_JS
} = DEFINITIONS;

const {
  CI_CD: {
    ITEMS: { GHA }
  },
  CLIENT_AND_SERVER_SIDE: {
    ITEMS: { GRAPHQL, NEXT_JS, SSR }
  },
  DATA_VISUALIZATION,
  HEADLESS_CMS: {
    ITEMS: { GATSBY }
  },
  SERVER_SIDE_DATABASES: {
    ITEMS: { MONGODB_MONGOOSE, NODE_EXPRESS, SQL }
  },
  TESTING: {
    ITEMS: { JEST, CYPRESS, REACT_TESTING_LIBRARY }
  },
  TOOLS_DOCUMENTATION: {
    ITEMS: { ESLINT, PRETTIER }
  },
  UI: {
    ITEMS: { REACT, REDUX, WCAG_AAA }
  }
} = DEFINITIONS;

export const TECHNICAL_SKILLS = {
  GROUPS: {
    CLIENT_AND_SERVER_SIDE,
    UI,
    SERVER_SIDE_DATABASES,
    TESTING,
    SECURITY,
    SYSTEM_INTEGRATIONS,
    CI_CD,
    TOOLS_DOCUMENTATION,
    HEADLESS_CMS,
    STYLING,
    DATA_VISUALIZATION,
    MISCELLANEOUS,
    HISTORICAL
  },
  SUMMARY: [
    VANILLA_JS.TITLE,
    TYPESCRIPT.TITLE,
    NODE_EXPRESS,
    ARCHITECTURE.TITLE,
    REACT,
    NEXT_JS,
    SQL,
    MONGODB_MONGOOSE,
    GRAPHQL,
    WCAG_AAA,
    SSR,
    REDUX,
    JEST,
    CYPRESS,
    REACT_TESTING_LIBRARY,
    SECURITY.TITLE,
    SECURITY.ITEMS.AUTHENTICATION,
    SECURITY.ITEMS.OWASP,
    SYSTEM_INTEGRATIONS.TITLE,
    ESLINT,
    PRETTIER,
    GHA,
    GATSBY
  ]
};

export default TECHNICAL_SKILLS;
